import type { IRecipeDemoRow } from '../types/recipe-demo-row';

export const recipeDemoRows: IRecipeDemoRow[] = [
  {
    id: 1,
    name: 'Ada Lovelace',
    category: 'BOOKS',
    price: 32,
    inStock: true,
    status: 'PAID',
    total: 180,
    age: 36,
    country: 'United Kingdom',
    role: 'ADMIN',
    lastActive: '2026-07-12',
    email: 'ada@example.com',
    createdAt: '2025-02-10',
    region: 'EU',
    revenue: 42000,
    amount: 180,
    active: true,
    approvedAmount: 200,
  },
  {
    id: 2,
    name: 'Grace Hopper',
    category: 'GAMES',
    price: 64,
    inStock: false,
    status: 'PENDING',
    total: 75,
    age: 28,
    country: 'United States',
    role: 'EDITOR',
    lastActive: '2026-06-18',
    email: 'grace@example.com',
    createdAt: '2024-11-03',
    region: 'US',
    revenue: 18000,
    amount: 75,
    active: false,
    approvedAmount: 50,
  },
  {
    id: 3,
    name: 'Katherine Johnson',
    category: 'BOOKS',
    price: 18,
    inStock: true,
    status: 'PAID',
    total: 120,
    age: 17,
    country: 'United States',
    role: 'VIEWER',
    lastActive: '2026-07-01',
    email: 'katherine@example.com',
    createdAt: '2026-01-15',
    region: 'US',
    revenue: 51000,
    amount: 120,
    active: true,
    approvedAmount: 120,
  },
  {
    id: 4,
    name: 'Margaret Hamilton',
    category: 'HARDWARE',
    price: 240,
    inStock: true,
    status: 'REFUNDED',
    total: 240,
    age: 42,
    country: 'Canada',
    role: 'ADMIN',
    lastActive: '2026-05-22',
    email: 'margaret@example.com',
    createdAt: '2023-08-21',
    region: 'CA',
    revenue: 73000,
    amount: 240,
    active: false,
    approvedAmount: 220,
  },
  {
    id: 5,
    name: 'Dorothy Vaughan',
    category: 'GAMES',
    price: 45,
    inStock: true,
    status: 'PAID',
    total: 310,
    age: 31,
    country: 'France',
    role: 'EDITOR',
    lastActive: '2026-07-14',
    email: 'dorothy@example.com',
    createdAt: '2025-09-09',
    region: 'EU',
    revenue: 67000,
    amount: 310,
    active: true,
    approvedAmount: 300,
  },
];
