import type { IBuilderFieldProps } from '@vojtechportes/react-query-builder';

export const demoFields: IBuilderFieldProps[] = [
  {
    field: 'CUSTOMER_COUNTRY',
    label: 'Customer country',
    type: 'LIST',
    operators: ['EQUAL', 'NOT_EQUAL', 'IN', 'NOT_IN', 'IS_NULL', 'IS_NOT_NULL'],
    value: [
      { value: 'CZ', label: 'Czech Republic' },
      { value: 'SK', label: 'Slovakia' },
      { value: 'DE', label: 'Germany' },
      { value: 'AT', label: 'Austria' },
    ],
    fieldComparison: {
      type: 'string',
      comparableFields: ['CUSTOMER_COUNTRY_CODE', 'DELIVERY_COUNTRY_CODE'],
    },
  },
  {
    field: 'CUSTOMER_COUNTRY_CODE',
    label: 'Customer country code',
    type: 'TEXT',
    operators: ['EQUAL', 'NOT_EQUAL', 'IS_NULL', 'IS_NOT_NULL'],
    fieldComparison: {
      type: 'string',
      comparableFields: ['CUSTOMER_COUNTRY', 'DELIVERY_COUNTRY_CODE'],
    },
  },
  {
    field: 'DELIVERY_COUNTRY_CODE',
    label: 'Delivery country code',
    type: 'TEXT',
    operators: ['EQUAL', 'NOT_EQUAL', 'IS_NULL', 'IS_NOT_NULL'],
    fieldComparison: {
      type: 'string',
      comparableFields: ['CUSTOMER_COUNTRY', 'CUSTOMER_COUNTRY_CODE'],
    },
  },
  {
    field: 'CUSTOMER_SEGMENTS',
    label: 'Customer segments',
    type: 'MULTI_LIST',
    operators: ['ALL_IN', 'ANY_IN', 'IN', 'NOT_IN'],
    value: [
      { value: 'B2B', label: 'B2B' },
      { value: 'Retail', label: 'Retail' },
      { value: 'Priority', label: 'Priority' },
      { value: 'Dormant', label: 'Dormant' },
    ],
  },
  {
    field: 'IS_IN_EU',
    label: 'Customer is in EU',
    type: 'BOOLEAN',
    operators: ['EQUAL', 'NOT_EQUAL'],
    fieldComparison: {
      type: 'boolean',
    },
  },
  {
    field: 'IS_VAT_PAYER',
    label: 'Customer is VAT payer',
    type: 'BOOLEAN',
    operators: ['EQUAL', 'NOT_EQUAL', 'IS_NULL', 'IS_NOT_NULL'],
    fieldComparison: {
      type: 'boolean',
    },
  },
  {
    field: 'CUSTOMER_CITY',
    label: 'Customer city',
    type: 'TEXT',
    operators: [
      'EQUAL',
      'NOT_EQUAL',
      'CONTAINS',
      'NOT_CONTAINS',
      'STARTS_WITH',
      'ENDS_WITH',
      'LIKE',
      'NOT_LIKE',
      'IS_NULL',
      'IS_NOT_NULL',
    ],
    fieldComparison: {
      type: 'string',
    },
  },
  {
    field: 'ORDER_TOTAL',
    label: 'Order total',
    type: 'NUMBER',
    operators: [
      'EQUAL',
      'NOT_EQUAL',
      'BETWEEN',
      'NOT_BETWEEN',
      'LARGER',
      'SMALLER',
      'LARGER_EQUAL',
      'SMALLER_EQUAL',
      'IS_NULL',
      'IS_NOT_NULL',
    ],
    fieldComparison: {
      type: 'number',
    },
  },
  {
    field: 'ORDER_APPROVAL_LIMIT',
    label: 'Order approval limit',
    type: 'NUMBER',
    operators: [
      'EQUAL',
      'NOT_EQUAL',
      'BETWEEN',
      'NOT_BETWEEN',
      'LARGER',
      'SMALLER',
      'LARGER_EQUAL',
      'SMALLER_EQUAL',
      'IS_NULL',
      'IS_NOT_NULL',
    ],
    fieldComparison: {
      type: 'number',
    },
  },
  {
    field: 'ORDER_MANUAL_REVIEW_THRESHOLD',
    label: 'Order manual review threshold',
    type: 'NUMBER',
    operators: [
      'EQUAL',
      'NOT_EQUAL',
      'BETWEEN',
      'NOT_BETWEEN',
      'LARGER',
      'SMALLER',
      'LARGER_EQUAL',
      'SMALLER_EQUAL',
      'IS_NULL',
      'IS_NOT_NULL',
    ],
    fieldComparison: {
      type: 'number',
    },
  },
  {
    field: 'ORDER_DISCOUNT_CAP',
    label: 'Order discount cap',
    type: 'NUMBER',
    operators: [
      'EQUAL',
      'NOT_EQUAL',
      'BETWEEN',
      'NOT_BETWEEN',
      'LARGER',
      'SMALLER',
      'LARGER_EQUAL',
      'SMALLER_EQUAL',
      'IS_NULL',
      'IS_NOT_NULL',
    ],
    fieldComparison: {
      type: 'number',
    },
  },
  {
    field: 'ORDER_CREATED_AT',
    label: 'Order created at',
    type: 'DATE',
    operators: [
      'EQUAL',
      'NOT_EQUAL',
      'BETWEEN',
      'NOT_BETWEEN',
      'LARGER',
      'SMALLER',
      'LARGER_EQUAL',
      'SMALLER_EQUAL',
      'IS_NULL',
      'IS_NOT_NULL',
    ],
    fieldComparison: {
      type: 'date',
    },
  },
  {
    field: 'COMPANY_NAME',
    label: 'Company name',
    type: 'TEXT',
    operators: [
      'EQUAL',
      'NOT_EQUAL',
      'CONTAINS',
      'NOT_CONTAINS',
      'STARTS_WITH',
      'ENDS_WITH',
      'IS_NULL',
      'IS_NOT_NULL',
    ],
    validation: {
      required: true,
    },
    fieldComparison: {
      type: 'string',
      comparableFields: ['CUSTOMER_CITY'],
    },
  },
  {
    field: 'DELIVERY_WINDOW',
    label: 'Delivery window',
    type: 'TEXT',
    operators: ['BETWEEN', 'NOT_BETWEEN'],
  },
  {
    field: 'RISK_NOTE',
    label: 'Risk note',
    type: 'STATEMENT',
    value: 'HAS_DEBT() AND LAST_PAYMENT_DAYS_AGO() > 30',
  },
  {
    field: 'FIRST_NAME',
    label: 'First name',
    type: 'TEXT',
    operators: [
      'EQUAL',
      'NOT_EQUAL',
      'CONTAINS',
      'NOT_CONTAINS',
      'STARTS_WITH',
      'ENDS_WITH',
    ],
    validation: {
      required: true,
    },
    usageLimit: {
      max: 1,
      scope: 'global',
    },
  },
];
