import { IBuilderComponentsProps } from '../../../builder';
import {
  BootstrapAddButton,
  BootstrapAlert,
  BootstrapCloneButton,
  BootstrapDropZone,
  BootstrapEmptyGroupDropZone,
  BootstrapGroup,
  BootstrapGroupHeaderOption,
  BootstrapHistoryControls,
  BootstrapInput,
  BootstrapLockToggle,
  BootstrapOutlinedButton,
  BootstrapPopover,
  BootstrapPopoverItem,
  BootstrapRemoveButton,
  BootstrapRule,
  BootstrapSelect,
  BootstrapSelectMulti,
  BootstrapSwitch,
  BootstrapText,
  BootstrapTextModeInput,
  BootstrapTextModeToggleContent,
} from './index';

export const createBootstrapComponentSet = (): IBuilderComponentsProps => ({
  Alert: BootstrapAlert,
  form: {
    Input: BootstrapInput,
    Select: BootstrapSelect,
    SelectMulti: BootstrapSelectMulti,
    Switch: BootstrapSwitch,
  },
  Add: BootstrapAddButton,
  Remove: BootstrapRemoveButton,
  CloneButton: BootstrapCloneButton,
  OutlinedButton: BootstrapOutlinedButton,
  TextModeToggleContent: BootstrapTextModeToggleContent,
  TextModeInput: BootstrapTextModeInput,
  LockToggle: BootstrapLockToggle,
  HistoryControls: BootstrapHistoryControls,
  Rule: BootstrapRule,
  Group: BootstrapGroup,
  GroupHeaderOption: BootstrapGroupHeaderOption,
  Text: BootstrapText,
  DropZone: BootstrapDropZone,
  EmptyGroupDropZone: BootstrapEmptyGroupDropZone,
  Popover: BootstrapPopover,
  PopoverItem: BootstrapPopoverItem,
});
